#!/bin/bash

# Copy RunInfo parameters and dragen bcl-convert stats to archive on server.
# USAGE: $0 FLOWCELL
#
# Reproduce parts of the scripts `cpRunInfoParameters.sh`created by 
# `cp_RunInfoParameters.pl`  and `cpBcl2FastqInfo.sh`, generated by 
# `cp_bcl2fastq_Parameters.pl`.

if [[ $(hostname) != 'spxp-app02.sainte-justine.intranet' ]]; then
    printf "Please use this script on spxp-app02.sainte-justine.intranet\n"
    exit
elif [[ -z ${FC} && -z ${BASEDIR} && -z ${PI} ]]; then
    printf "Please set values for \$FLOWCELL and \$BASEDIR.\n"
    exit
fi

# cpRunInfoParameters.sh créé par cp_RunInfoParameters.pl:
rsync -uva --progress \
    --exclude Data \
    --exclude Thumbnail_Images \
    --exclude Logs \
    --exclude Recipe \
    ${BASEDIR}/${FC} \
    /staging/bioinformatics/databases/flowcell_managment/_Illumina_HiSeq/_runInfoParameters/
chmod 777 -R /staging/bioinformatics/databases/flowcell_managment/_Illumina_HiSeq/_runInfoParameters/${FC} 
printf "\nCopied RunInfo parameters...\n"

# cpBcl2FastqInfo.sh créé par cp_bcl2fastq_Parameters.pl
for f in \
    ${WORKDIR}/${FC}/${FC_SHORT}.bcl-convert.log \
    ${WORKDIR}/${FC}/SampleNames.txt \
    ${WORKDIR}/${FC}/*.csv \
    ${WORKDIR}/${FC}/1.fastq/Logs* \
    ${WORKDIR}/${FC}/1.fastq/Reports*
do
    rsync -a --progress ${f} /staging/bioinformatics/databases/flowcell_managment/_Illumina_HiSeq/_bcl2fastq_pbs_csv_stats/${PI}/${FC}/
done
chmod 777 -R /staging/bioinformatics/databases/flowcell_managment/_Illumina_HiSeq/_bcl2fastq_pbs_csv_stats/${PI}/${FC}
printf "\nCopied dragen bcl-convert stats...\n"

printf "\nCopier-coller le message suivant dans un courriel et envoyer au labo."
printf "\nMettre en p.j. le fichier 'Reports.xlsx' généré par 'assemble_report.py'\n"
echo "
From: Quang-Hien Le (HSJ)
To: Charles Prive (HSJ) <charles.prive.hsj@ssss.gouv.qc.ca>; Elodie Hip-Ki (HSJ) <elodie.hip-ki.hsj@ssss.gouv.qc.ca>; Sandra Laurent (HSJ) <sandra.laurent.hsj@ssss.gouv.qc.ca>; Ariane Page-Sabourin (HSJ) <ariane.page-sabourin.hsj@ssss.gouv.qc.ca>; Alexandre Dionne-Laporte (HSJ) <alexandre.dionne-laporte.hsj@ssss.gouv.qc.ca>; Maripier Hainse (HSJ) <maripier.hainse.hsj@ssss.gouv.qc.ca>; Rene Allard GQ (HSJ) <rene.allard.hsj@ssss.gouv.qc.ca>
Subject: [${PI}] Stats de la FC ${FC}

Bonjour,

Voici les stats de déconvolution-conversion de la FC ${FC} :

Cordialement,
"
