#!/usr/bin/env python3
"""
Control the Quality of DRAGEN BCL-convert. Check the yield per index and 
reports several statistics from `Reports/Demultiplex_Stats.csv` generated by
`dragen --bcl-conversion-only`.

USAGE: qc_demultiplex_stats.py --help # And the rest is handled by `argparse`
"""

import sys
import os
import argparse
import logging
import pandas as pd
import plotly
import plotly.graph_objects as go

__version__ = "0.1"


def parse_args():
    """
    Parse command-line options
    """
    parser = argparse.ArgumentParser(description="Quality Control of BCL-convert's Demultiplex_Stats")
    parser.add_argument('--file', '-f', nargs='?', default='Demultiplex_Stats.csv', 
                        help="Dragen BCL-convert demultiplexing report. Default='Demultiplex_Stats.csv'")
    parser.add_argument('--logging-level', '-l', dest='level', default='info',
                        help="Logging level (str), can be 'debug', 'info', 'warning'. Default='info'")
    return parser.parse_args()


def configure_logging(level):
    """
    Set logging level, based on the level names of the `logging` module.
    - level (str): 'debug', 'info' or 'warning'
    """
    if level == 'debug':
        level_name = logging.DEBUG
    elif level == 'info':
        level_name = logging.INFO
    else:
        level_name = logging.WARNING
    logging.basicConfig(level=level_name, 
                        format='[%(asctime)s] %(levelname)s: %(message)s', 
                        datefmt='%Y-%m-%d@%H:%M:%S')


def plot_plotly_bar(df, threshold=600000000):
    """
    Plot bar chart using Plotly as a PNG file
    - `df`: Two-column Pandas DataFrame ['SampleID', '# Reads']
    - `threshold`: value to mark as threshold. Default=600,000,000
    - Returns: 0
    """
    df.columns = ['SampleID', '# Reads']
    fig = go.Figure([go.Bar(x=df['SampleID'], y=df['# Reads'])])
    fig.update_layout(title={'text': 'Number of reads per SampleID', 'x': 0.5, 'xanchor': 'center'},
                      xaxis_title='SampleID',
                      yaxis_title='Number of Reads')
    bar_colors = ['red' if val < threshold else 'orange' for val in df['# Reads']]
    fig.update_traces(marker_color=bar_colors, 
                      marker_line_color='rgb(8,48,107)',
                      marker_line_width=1.5,
                      opacity=0.6)
    fig.add_shape(type="line",
                  x0=0, x1=1, xref='paper',
                  y0=threshold, y1=threshold, yref='y',
                  line=dict(color="dark grey", width=1, dash="dash"))
    fig.update_traces(marker_color=bar_colors)
    #fig.write_image('demux_reads_per_sample-bar.png')
    plotly.offline.plot(fig, filename='demux_reads_per_sample-bar.html')
    return 0


def plot_ascii_bar(data):
    """
    Plot bar chart of `dataframe` using ASCII art.
    Code and text  by Alex Chan from [Drawing ASCII bar charts]
    (https://alexwlchan.net/2018/ascii-bar-charts/)
    - `data` : List of tuples [('Labels', 'Counts'), ('Labels', 'Counts'),...]
    - Returns: (str) ASCII art bar plot
    """
    bar_plot_str = ''
    max_value = max(count for _, count in data)
    increment = max_value / 25
    longest_label_length = max(len(label) for label, _ in data)

    for label, count in data:
        # ASCII block elements are chunks of 8: work out how many fractions
        # of 8 we need https://en.wikipedia.org/wiki/Block_Elements
        #
        bar_chunks, remainder = divmod(int(count * 8 / increment), 8)

        # First draw the full width chunks
        #
        bar = '█' * bar_chunks

        # Then add the fractional part. The Unicode code points for block 
        # elements are 8/8, 7/8, 6/8, ... , so we need to work backwards.
        #
        if remainder > 0:
            bar += chr(ord('█') + (8 - remainder))

        # If the bar is empty, add a left one-eighth block
        #
        bar = bar or  '▏'

        bar_plot_str += f"{label.rjust(longest_label_length)} ▏ {count:#4d} {bar}\n"
        
    return bar_plot_str


def main():
    """
    Main function
    """
    args = parse_args()
    configure_logging(args.level)

    df_demux_stats0 = pd.read_csv(args.file)
    df_demux_stats0['SampleID'] = df_demux_stats0['SampleID'].astype(str)
    df_demux_stats = df_demux_stats0.groupby('SampleID').sum('# Reads').reset_index()[['SampleID', '# Reads', '% Reads']]
    df_demux_stats['Mean % Perfect Index Reads'] = df_demux_stats0.groupby('SampleID').mean('% Perfect Index Reads').reset_index()['% Perfect Index Reads']

    plot_plotly_bar(df_demux_stats[['SampleID', '# Reads']])
    data = [] # Create list of tuples for `plot_ascii_bar(list_oftuples)`
    for index, row in df_demux_stats.iterrows():
        data.append((row['SampleID'], row['# Reads']))
    print(plot_ascii_bar(data))

if __name__ == '__main__':
    sys.exit(main())
